#ifndef RAT_GEN_H
#define RAT_GEN_H

/* This file is generated by rat-sync. */
#define RAT_GEN_FINGERPRINT 0x3A85528C8BE768B0ULL
#define RAT_GEN_PACKET_COUNT 1u

#define RAT_ID_RATSAMPLE 0x0Cu

#endif  /* RAT_GEN_H */
